user:
  name:
    max_length: 255
  email:
    max_length: 255
  expired_time: 2
  password:
    min_length: 6
user_helper:
  gravatar:
    size: 80
users:
  index:
    per_page: 10
  show_follow:
    size: 30
  user:
    size: 50
post:
  max_length: 140
  per_page: 10
  picture_size: 5
  user_image_size: 50
comments:
  user:
    picture_size: 30
